# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'Messages' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Messages

  target 'MessagesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MessagesUITests' do
    # Pods for testing
  end

pod 'MessageKit'
pod 'InputBarAccessoryView'
pod 'Swifter', '~> 1.5'
pod 'CryptoSwift', '~> 1.3.8'

end
